### ISSUE TITLE
Consider adding modular Firebase SDK 9 support

### ISSUE THREAD

**Issue by jquesada2016** [codediodeio/sveltefire#51]
This will be a breaking change going forward with this library. It is possible to still make this library work, however, a custom object that has all of the expected methods must be passed in. For now, Firebase SDK 9 has a `compat` surface, so users can use that in the meantime, but doesn't reap the benefits of the tree-shaking.

**Comment by LockedThread** [comment]
I second this

**Comment by madeleineostoja** [comment]
imo a breaking change for Firebase 9 isn’t an issue. Users that need to stick with Firebase 8 for whatever reason can stay on an old version of sveltefire, this is exactly the reason semver exists. 

Firebase 9 support should be implemented fully, rather than trying to monkeypatch compat with Firebase 8

**Comment by codediodeio** [comment]
Firebase 9 support added in #74

**Comment by Kimeiga** [comment]
Hey Jeff, would there be any chance you could add more documentation to the Readme for how to add new documents to collections and other adding stuff using the new structure of sveltefire? I don't see the sveltefire example repo on github any more
